# Generated by Django 2.2 on 2019-06-08 02:27

import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('slug_name', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reputation', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[apps.utils.validators.reputation_validator])),
                ('category', models.IntegerField(choices=[(0, 'Arte'), (1, 'Tecnología'), (2, 'Informática'), (3, 'Electrónica'), (4, 'Deportes'), (5, 'Diseño'), (6, 'Negocio'), (7, 'Comunidad'), (8, 'Educación'), (9, 'Videojuegos'), (10, 'Industria'), (11, 'Música'), (12, 'Fotografía'), (13, 'Literatura'), (14, 'Científico'), (15, 'Animales'), (16, 'Naturaleza'), (17, 'Caridad')])),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
