# Generated by Django 2.2 on 2019-05-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ProfileWorker'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ProfileCreator'),
        ),
        migrations.AddField(
            model_name='precedence',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Activity'),
        ),
        migrations.AddField(
            model_name='precedence',
            name='precedence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedence_activity', to='projects.Activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
