# Generated by Django 2.2 on 2019-05-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190508_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='position',
            new_name='job',
        ),
    ]
