# Generated by Django 2.2 on 2019-05-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190508_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Waiting')], max_length=30),
        ),
    ]
