# Generated by Django 2.2 on 2019-05-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_publication_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='likes',
        ),
    ]
