# Generated by Django 2.2 on 2019-05-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Waiting')]),
        ),
    ]
