# Generated by Django 2.2 on 2019-04-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='country',
        ),
    ]
