# Generated by Django 2.2 on 2019-04-23 04:32

import apps.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='statics.users')),
                ('biography', models.TextField(blank=True, null=True)),
                ('born_date', models.DateField()),
                ('verified', models.BooleanField(default=False, help_text='Verificated profiles have better reputation than normal profiles.')),
                ('reputation', models.SmallIntegerField(default=0, validators=[apps.utils.validators.reputation_validator])),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country')),
                ('projects', models.ManyToManyField(through='projects.Worker', to='projects.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='statics.users')),
                ('biography', models.TextField(blank=True, null=True)),
                ('born_date', models.DateField()),
                ('verified', models.BooleanField(default=False, help_text='Verificated profiles have better reputation than normal profiles.')),
                ('reputation', models.SmallIntegerField(default=0, validators=[apps.utils.validators.reputation_validator])),
                ('Country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
