# Generated by Django 2.2 on 2019-05-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190508_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
